apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.appName }}
  description: ${{ values.description }}
  annotations:
    # Repositório GitHub
    github.com/project-slug: ${{ values.githubUser }}/${{ values.appName }}
    # Credenciais ADO — host/org
    dev.azure.com/host-org: dev.azure.com/${{ values.adoOrg }}
    # Projeto ADO
    dev.azure.com/project: ${{ values.adoProject }}
    # Nome da pipeline criada pelo template: <adoOrg>.<appName>
    dev.azure.com/build-definition: ${{ values.adoOrg }}.${{ values.appName }}
  tags:
    - quarkus
    - java
spec:
  type: service
  lifecycle: development
  owner: user:guest
