integrations:
  github:
    - host: github.com
      token: ${GITHUB_TOKEN}
  azure:
    - host: dev.azure.com
      credentials:
        - organizations:
            - ${AZURE_DEVOPS_ORG}
          personalAccessToken: ${AZURE_DEVOPS_PAT}
azureDevOps:
  host: dev.azure.com
  organization: ${AZURE_DEVOPS_ORG}
  token: ${AZURE_DEVOPS_PAT}
proxy:
  endpoints:
    /azure-devops:
      target: https://dev.azure.com
      changeOrigin: true
      allowedMethods: [GET, POST, DELETE, PATCH]
      credentials: dangerously-allow-unauthenticated
      headers:
        Authorization: "Basic OkFTNk1tZ0FVc29BYkVGV0JHeUkzREZNNHhaR203dngxUFRjUHJYdGV5R2Jjek1aOVFiRDBKUVFKOTlDRUFDQUFBQUFBQUFBQUFBQVNBWkRPM1AwYw=="
catalog:
  rules:
    - allow:
        - Component
        - System
        - Group
        - User
        - Resource
        - Location
        - Template
        - API
  locations:
    - type: url
      #target: https://raw.githubusercontent.com/${GITHUB_USER}/devhub-github-azuredevops-demo/main/templates/all-templates.yaml
      target: https://github.com/sandrotanaka/devhub-github-azuredevops-demo/blob/main/templates/all-templates.yaml
    - type: url
      target: https://github.com/sandrotanaka/devhub-github-azuredevops-demo/blob/main/catalog/users.yaml
  providers:
    azureDevOps:
      default:
        organization: ${AZURE_DEVOPS_ORG}
        project: ${AZURE_DEVOPS_PROJECT}
        repository: '*'
        path: /catalog-info.yaml
        schedule:
          frequency:
            minutes: 30
          timeout:
            minutes: 3
backend:
  reading:
    allow:
      - host: raw.githubusercontent.com
      - host: dev.azure.com
auth:
  environment: production
  #dangerouslyAllowSignInWithoutUserInCatalog: true
  providers:
    github:
      production:
        clientId: ${GITHUB_CLIENT_ID}
        clientSecret: ${GITHUB_CLIENT_SECRET}
        signIn:
          resolvers:
            - resolver: usernameMatchingUserEntityName
            #- resolver: emailMatchingUserEntityProfileEmail
            #- resolver: emailLocalPartMatchingUserEntityName
    guest:
      dangerouslyAllowOutsideDevelopment: true
signInPage: github
permission:
  enabled: false
githubPullRequests:
  authorizationToken: ${GITHUB_TOKEN}