plugins:
  - disabled: false
    package: oci://ghcr.io/redhat-developer/rhdh-plugin-export-overlays/backstage-community-plugin-azure-devops:bs_1.45.3__0.23.0
  - disabled: false
    package: oci://ghcr.io/redhat-developer/rhdh-plugin-export-overlays/backstage-community-plugin-azure-devops-backend:bs_1.45.3__0.23.0
  - disabled: false
    package: ./dynamic-plugins/dist/backstage-plugin-scaffolder-backend-module-github-dynamic
  - disabled: false
    package: ./dynamic-plugins/dist/roadiehq-scaffolder-backend-module-http-request-dynamic
